#!/bin/bash
#
# This shell script must be run as root

if test -f config.custom ; then
	. config.custom
else
	. config
fi

DIR=$(pwd)
ROOTDIR=/
KVM=kvm-xfstests/test-appliance
RAW_ROOT_FS=$DIR/root_fs.raw
ROOT_FS=$KVM/root_fs.img
COMPAT="-o compat=0.10"

useradd fsgqa
#echo 'fsgqa:x:31415:31415:fsgqa user:/home/fsgqa:/bin/bash' >> $ROOTDIR/etc/passwd
#echo 'fsgqa:!::0:99999:7:::' >> $ROOTDIR/etc/shadow
#echo 'fsgqa:x:31415:' >> $ROOTDIR/etc/group
#echo 'fsgqa:!::' >> $ROOTDIR/etc/gshadow
mkdir $ROOTDIR/home/fsgqa
chown 31415:31415 $ROOTDIR/home/fsgqa
chmod 755 $ROOTDIR/root

cp $ROOTDIR/lib/systemd/system/serial-getty@.service \
	$ROOTDIR/etc/systemd/system/telnet-getty@.service
sed -i -e '/ExecStart/s/agetty/agetty -a root/' \
    -e 's/After=rc.local.service/After=kvm-xfstests.service/' \
	$ROOTDIR/lib/systemd/system/serial-getty@.service
sed -i -e '/ExecStart/s/agetty/agetty -a root/' \
    -e 's/After=rc.local.service/After=network.target/' \
	$ROOTDIR/etc/systemd/system/telnet-getty@.service
dpkg --purge gcc-4.7-base gcc-4.8-base
systemctl enable kvm-xfstests.service
systemctl enable telnet-getty@ttyS1.service
systemctl enable telnet-getty@ttyS2.service
systemctl enable telnet-getty@ttyS3.service
find $ROOTDIR/usr/share/doc -type f | grep -v copyright | xargs rm
find $ROOTDIR/usr/share/doc -mindepth 2 -type l | xargs rm
find $ROOTDIR/usr/share/doc -type d | xargs rmdir --ignore-fail-on-non-empty -p
rm -rf $ROOTDIR/usr/share/man
find $ROOTDIR/var/log -type f | xargs rm
if test -n "$OUT_TAR"; then
    rm -f $ROOTDIR/dev $ROOTDIR/proc
    mkdir $ROOTDIR/dev $ROOTDIR/proc
    mknod -m 622 $ROOTDIR/dev/console c 5 1
    mknod -m 666 $ROOTDIR/dev/null c 1 3
    mknod -m 666 $ROOTDIR/dev/zero c 1 5
    mknod -m 666 $ROOTDIR/dev/ptmx c 5 2
    mknod -m 666 $ROOTDIR/dev/tty c 5 0
    mknod -m 444 $ROOTDIR/dev/random c 1 8
    mknod -m 444 $ROOTDIR/dev/urandom c 1 9
    chown root:tty $ROOTDIR/dev/{console,ptmx,tty}
    if test "$(uname -m)" = x86_64 ; then
	rm /lib64/ld-linux-x86-64.so.2
	mkdir -p /lib64
	ln -s /lib/x86_64-linux-gnu/ld-linux-x86-64.so.2 /lib64/
    fi
    if test -f $ROOTDIR/sbin/ldconfig.real ; then
	mv $ROOTDIR/sbin/ldconfig.real $ROOTDIR/sbin/ldconfig
	ed $ROOTDIR/var/lib/dpkg/diversions <<EOF > /dev/null 2>&1
/^\/sbin\/ldconfig.real$/
.-1,.+1d
wq
EOF
    fi
    if test -f $ROOTDIR/usr/bin/ldd.REAL ; then
	mv $ROOTDIR/usr/bin/ldd.REAL $ROOTDIR/usr/bin/ldd
	ed $ROOTDIR/var/lib/dpkg/diversions <<EOF > /dev/null 2>&1
/^\/usr\/bin\/ldd.REAL$/
.-1,.+1d
wq
EOF
    fi
fi
